const WholeSalesTypes={
    GETINDUSTRIES_START:'GETINDUSTRIES_START',
    GETINDUSTRIES_SUCCESS:'GETINDUSTRIES_SUCESS',
    GETINDUSTRIES_FAILURE:'GETINDUSTRIES_FAILURE',
}

export default WholeSalesTypes;