const WholeSalesTypes={
    GETINDUSTRIES_START:'GETINDUSTRIES_START',
    GETINDUSTRIES_SUCCESS:'GETINDUSTRIES_SUCESS',
    GETINDUSTRIES_FAILURE:'GETINDUSTRIES_FAILURE',
    SALE_START:'SALE_START',
    SALE_SUCCESS:'SALE_SUCCESS',
    SALE_STOP:'SALE_STOP',
    GETALL_CLIENT_START:'GETALL_CLIENT_START',
    GETALL_CLIENT_SUCCESS:'GETALL_CLIENT_SUCCESS',
    GETALL_CLIENT_FAILURE:'GETALL_CLIENT_FAILURE',
    GETALL_TARGETMARKET_START:'GETALL_TARGETMARKET_START',
    GETALL_TARGETMARKET_SUCCESS:'GETALL_TARGETMARKET_SUCCESS',
    GETALL_TARGETMARKET_FAILURE:'GETALL_TARGETMARKET_FAILURE',
    INSERT_CAMPAIGN_START:'INSERT_CAMPAIGN_START',
    INSERT_CAMPAIGN_SUCCESS:'INSERT_CAMPAIGN_SUCCESS',
    INSERT_CAMPAIGN_FAILURE:'INSERT_CAMPAIGN_FAILURE',
}

export default WholeSalesTypes;