const UserActionTypes={
    SIGN_IN_START:'SIGN_IN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    PASSWORD_RESET_START:'PASSWORD_RESET_START',
    PASSWORD_RESET_SUCCESS:'PASSWORD_RESET_SUCCESS',
    PASSWORD_RESET_STOP:'PASSWORD_RESET_STOP',
}

export default UserActionTypes;

